# Generated by Django 5.0.7 on 2024-07-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=50)),
                ("rating", models.CharField(blank=True, max_length=50, null=True)),
                ("sold", models.CharField(blank=True, max_length=50, null=True)),
                ("link", models.URLField()),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
